# Generated by Django 5.2.17 on 2026-09-17 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category__order', 'category__name', '-created_at']},
        ),
    ]
