"""
Django settings for lielena project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# In production, set the DJANGO_SECRET_KEY environment variable instead of
# editing this file. The fallback below is fine for local development only.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-r-rx^afj3wfb&02z1s5f=fl-fcplz=_*j$88vy3e0l%$u#zokq',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Set DJANGO_DEBUG=False in your production environment.
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get(
        'DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1'
    ).split(',') if h.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'shop',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lielena.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'shop.context_processors.nav_categories',
            ],
        },
    },
]

WSGI_APPLICATION = 'lielena.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
#
# Locally, with no DATABASE_URL set, this uses sqlite so you can develop
# without any setup. In production (Vercel), set DATABASE_URL to your
# Supabase connection string and it switches to that automatically.

import dj_database_url

DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Addis_Ababa'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (product photos uploaded via the admin)
#
# Locally (no Supabase env vars set) these are saved to the media/ folder
# on disk, same as before. In production, Vercel's filesystem is read-only
# and ephemeral, so uploaded photos MUST live somewhere external — this
# switches to Supabase Storage (S3-compatible) automatically whenever the
# SUPABASE_STORAGE_* env vars are present. New admin uploads go straight
# there too, no extra steps needed.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

SUPABASE_STORAGE_ENDPOINT = os.environ.get('SUPABASE_STORAGE_ENDPOINT')
SUPABASE_STORAGE_BUCKET = os.environ.get('SUPABASE_STORAGE_BUCKET', 'product-images')
SUPABASE_ACCESS_KEY_ID = os.environ.get('SUPABASE_ACCESS_KEY_ID')
SUPABASE_SECRET_ACCESS_KEY = os.environ.get('SUPABASE_SECRET_ACCESS_KEY')

# The project ref is the subdomain in your Supabase project URL, e.g. for
# https://kqueiofsjbiznycmxcnj.supabase.co it's "kqueiofsjbiznycmxcnj".
# Used to build the PUBLIC browser-facing image URL, which is different
# from the S3 upload endpoint above. You can override it in production
# with a SUPABASE_PROJECT_REF env var if this project's ref ever changes.
SUPABASE_PROJECT_REF = os.environ.get(
    'SUPABASE_PROJECT_REF',
    'kqueiofsjbiznycmxcnj',
)

STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

if SUPABASE_STORAGE_ENDPOINT and SUPABASE_ACCESS_KEY_ID:
    STORAGES["default"] = {
        # Custom subclass of S3Boto3Storage (see shop/storage.py) that
        # still uploads via the S3-compatible endpoint below, but returns
        # Supabase's public object URL (not the S3 endpoint URL) when
        # Django asks for image.url — that's the part that was broken.
        "BACKEND": "shop.storage.SupabasePublicStorage",
    }
    AWS_ACCESS_KEY_ID = SUPABASE_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY = SUPABASE_SECRET_ACCESS_KEY
    AWS_STORAGE_BUCKET_NAME = SUPABASE_STORAGE_BUCKET
    AWS_S3_ENDPOINT_URL = SUPABASE_STORAGE_ENDPOINT
    AWS_S3_REGION_NAME = os.environ.get('SUPABASE_STORAGE_REGION', 'us-east-1')
    AWS_DEFAULT_ACL = 'public-read'
    AWS_QUERYSTRING_AUTH = False
    AWS_S3_FILE_OVERWRITE = False
else:
    STORAGES["default"] = {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    }

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}